import { Poppins, Arya, Montserrat } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const arya = Arya({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arya",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "V & P Law Firm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${arya.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
